# The URL the site will be built for
#base_url = "https://wake-poc.lgbtqdemocrats.com/"
base_url = "/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "tabi"
title = "LGBTQ+ Democrats of Wake County"
description = "Lesbian Gay Bisexual Transgender Queer + Democrats of Wake County"
author = "LGBTQ+ Dems of Wake"
generate_feeds = true
minify_html = true
default_language = "en"
taxonomies = [{name = "tags", feed = true}]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
 highlight_code = true
bottom_footnotes = true
highlight_theme = "css"
smart_punctuation = true

[extra]
# Put all your custom variables here
email = "lgbtqdemsofwake@gmail.com"

override_serif_with_sans = false
theme_switcher = true
default_theme = ""

# This is the menu across the top
menu = [
#  { name = "calendar", url = "calendar", trailing_slash = true },
  { name = "about", url = "about", trailing_slash = true },
  { name = "blog", url= "blog", trailing_slash = true},
  { name = "join", url="donate", trailing_slash = true},
#  { name = "docs", url="documents", trailing_slash = true},
  { name = "projects", url = "projects", trailing_slash = true},
]

full_content_in_feed = true

encode_plaintext_email = true

copyright = "$TITLE © $CURRENT_YEAR $AUTHOR $SEPARATOR All rights reserved."

footer_menu = [
  { url = "sitemap.xml", name = "sitemap", trailing_slash = false },
#  { url = "privacy", name = "privacy", trailing_slash = true },
  { url = "docs", name = "docs", trailing_slash = true },
  { url = "https://www.lgbtqdemocrats.org/", name = "NC", trailing_slash = false },
  { name = "newsletter", url= "https://us12.campaign-archive.com/home/?id=c5b01a5ca5&u=a3417ec30f0e81ba574dadfce", trailing_slash = false},
]

# Choose the colourscheme (skin) for the theme. Default is "teal".
# Skin available: blue, lavender, mint, red, sakura, teal, monochrome, lowcontrast_orange, lowcontrast_peach, lowcontrast_pink, indigo_ingot, evangelion
# See them live and learn how to create your own: https://welpo.github.io/tabi/blog/customise-tabi/#skins
# WARNING! "lowcontrast" skins, while aesthetically pleasing, may not provide optimal
# contrast (in light theme) for readability and might not be suitable for all users.
# Furthermore, low contrasting elements will affect your Google Lighthouse rating.
# All other skins have optimal contrast.
skin = ""
# Set browser theme colour. Can be a single colour or [light, dark].
# Note: Bright colors may be ignored in dark mode.
# More details: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
# browser_theme_color = "#087e96"  # Example of single value.
# browser_theme_color = ["#ffffff", "#000000"]  # Example of light/dark colours.

# List additional stylesheets to load site-wide.
# These stylesheets should be located in your site's `static` directory.
# Example: stylesheets = ["extra1.css", "path/extra2.css"]
# You can load a stylesheet for a single post by adding it to the [extra] section of the post's front matter, following this same format.
stylesheets = []

# Remote repository for your Zola site.
# Used for `show_remote_changes` and `show_remote_source` (see below).
# Supports GitHub, GitLab, Gitea, and Codeberg.
# remote_repository_url = "https://github.com/welpo/tabi"
# Set this to "auto" to try and auto-detect the platform based on the repository URL.
# Accepted values are "github", "gitlab", "gitea", and "codeberg".
remote_repository_git_platform = "auto"  # Defaults to "auto".

